COMFYUI_VERSION := v0.3.77
CUSTOM_NODES_JSON := code/comfyui/v0.3.77/custom_nodes.json
OSS_COMFYUI_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma
OSS_COMFYUI_DEEPGPU_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma-deepgpu

include ../shared/Makefile.common
