COMFYUI_VERSION := v0.3.77
CUSTOM_NODES_JSON := comfyui/v0.3.77/custom_nodes.json
OSS_COMFYUI_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma
OSS_COMFYUI_DEEPGPU_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma-deepgpu
CAP_SYSTEM_VERSION := 1.6.8

include ../shared/Makefile.common
