FROM alpine/git:2.36.2 AS codes

WORKDIR /root

ENV SD_DIR="/root/stable-diffusion-webui"
ENV REPO_DIR="${SD_DIR}/repositories"

RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git ${SD_DIR} && \
    cd ${SD_DIR} && \
    git checkout "v1.10.1"

# repositories
RUN git clone https://github.com/Stability-AI/stablediffusion.git ${REPO_DIR}/stable-diffusion-stability-ai && \
    cd ${REPO_DIR}/stable-diffusion-stability-ai && \
    git reset --hard cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf

RUN git clone https://github.com/Stability-AI/generative-models.git ${REPO_DIR}/generative-models && \
    cd ${REPO_DIR}/generative-models && \
    git reset --hard 45c443b316737a4ab6e40413d7794a7f5657c19f

RUN git clone https://github.com/salesforce/BLIP.git ${REPO_DIR}/BLIP && \
    cd ${REPO_DIR}/BLIP && \
    git reset --hard 48211a1594f1321b00f14c9f7a5b4813144b2fb9

RUN git clone https://github.com/crowsonkb/k-diffusion.git ${REPO_DIR}/k-diffusion && \
    cd ${REPO_DIR}/k-diffusion && \
    git reset --hard ab527a9a6d347f364e3d185ba6d714e22d80cb3c

RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets ${REPO_DIR}/stable-diffusion-webui-assets && \
    cd ${REPO_DIR}/stable-diffusion-webui-assets && \
    git reset --hard 6f7db241d2f8ba7457bac5ca9753331f0c266917

FROM python:3.10.16-slim AS models

RUN apt update && apt install -y aria2

COPY --from=registry.cn-hangzhou.aliyuncs.com/ohyee/fc-demo:fc-comfyui-sd1.5-v1 "/built-in/models/checkpoints/sd-v1-5-inpainting.ckpt" "/models/checkpoints/sd-v1-5-inpainting.ckpt"

FROM python:3.10.16-slim AS dependencies

WORKDIR /root

# 安装 rust 环境
RUN --mount=type=cache,target=/var/cache/apt \
    apt update && \
    apt install -y curl gcc g++ build-essential
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

# 升级pip并初始化venv虚拟环境
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    python3 -m venv venv

# 安装cu124最新PyTorch及相关包
RUN --mount=type=cache,target=/root/.cache/pip \
    venv/bin/pip install --no-cache-dir torch torchvision xformers \
    --extra-index-url https://download.pytorch.org/whl/cu124

# 安装transformers, 其依赖项tokenizers需要rust环境
RUN --mount=type=cache,target=/root/.cache/pip \
    . /venv/bin/activate && \
    export PATH="/root/.cargo/bin:$PATH" && \
    pip install transformers==4.15.0

# 安装 源码 所使用的依赖
#    find . -type f -name "requirements.txt" | xargs -I {} cat {} | tr -d '\r' | sed 's/>/=/g' |  sort -u | awk -F '==' '! /^(#|-|\s*$)/ {sub(/^[ \t]+|[ \t]+$/, "", $0); if (!seen[$1]++) print}' | xargs
RUN --mount=type=cache,target=/root/.cache/pip \
    venv/bin/pip install --no-cache-dir \
    accelerate albumentations==0.4.3 blendmodes clean-fid clip-anytorch diskcache einops \
    facexlib fairscale==0.4.4 fastapi==0.90.1 GitPython gradio==3.13.2 imageio==2.9.0 \
    imageio-ffmpeg==0.4.2 inflection invisible-watermark==0.1.5 jsonmerge kornia lark \
    numpy omegaconf open-clip-torch opencv-python piexif Pillow pillow-avif-plugin==1.4.3 \
    protobuf==3.20.0 psutil pudb==2019.2 pycocoevalcap pytorch_lightning pytorch-lightning==1.4.2 \
    requests resize-right safetensors scikit-image scipy streamlit==0.73.1 streamlit-drawable-canvas==0.8.0 \
    test-tube==0.7.5 timm==0.4.12 tomesd torch torchdiffeq torchmetrics==0.6 torchsde \
    torchvision tqdm transformers==4.15.0 wandb webdataset==0.2.5

FROM agent AS agent

FROM python:3.10.16-slim AS base

WORKDIR /root

RUN --mount=type=cache,target=/var/cache/apt \
    apt update && \
    apt install -y \
    git curl wget jq ffmpeg gcc g++ build-essential libgl1 libglib2.0-0

ENV WORK_DIR='/root'
ENV SD_DIR="${WORK_DIR}/stable-diffusion-webui"
ENV VENV_DIR="${WORK_DIR}/venv"
ENV AGENT_DIR="${WORK_DIR}/agent"
# MNT_DIR is initialized in s.yaml, using env var-'MODEL_ASSET_DIR'

ENV BUILT_IN_DIR="/built-in"
COPY --from=models /models ${BUILT_IN_DIR}/models
COPY --from=dependencies ${VENV_DIR} ${VENV_DIR}
COPY --from=codes ${SD_DIR} ${SD_DIR}
COPY --from=agent ${AGENT_DIR} ${AGENT_DIR}
# TODO add pip path of venv

ENTRYPOINT [ "/bin/bash", "-c", "${AGENT_DIR}/entrypoint.bash" ]
