COMFYUI_VERSION := v0.16.4
CUSTOM_NODES_JSON := comfyui/v0.16.4/custom_nodes.json
OSS_COMFYUI_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma
OSS_COMFYUI_DEEPGPU_BASE_DIR := base/comfyui/$(COMFYUI_VERSION)-gamma-deepgpu
CAP_SYSTEM_VERSION := 2.0.0
VISION_PLAID_VERSION := 1.2.1
BITFORGE_VERSION := 0.2.4
VISION_PLAID_EXTRA_PACKAGES := flashinfer-python flashinfer-cubin
BUILTIN_DEPENDENCY_VERSION := 2.0.0-vp1.2.1

include ../shared/Makefile.common
