FROM alpine/git:2.36.2 AS codes

WORKDIR /root

ENV COMFYUI_DIR="/root/comfyui"

RUN git clone https://github.com/comfyanonymous/ComfyUI.git ${COMFYUI_DIR} && \
    cd ${COMFYUI_DIR} && \
    git checkout "v0.3.59"

# add built-in custom-nodes
RUN cd ${COMFYUI_DIR}/custom_nodes && \
    git clone https://github.com/ltdrdata/ComfyUI-Manager.git && \
    cd ComfyUI-Manager && \
    git checkout "3.35"

# 核心功能插件
RUN cd ${COMFYUI_DIR}/custom_nodes && \

    # ControlNet 支持 - 精确控制图像生成
    git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git && \

    # 图像处理工具套件
    git clone https://github.com/WASasquatch/was-node-suite-comfyui.git && \

    # 自定义脚本和UI增强
    git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git && \


    git clone https://github.com/chflame163/ComfyUI_LayerStyle.git && \

    git clone https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git && \

    git clone https://github.com/yolain/ComfyUI-Easy-Use.git && \

    git clone https://github.com/rgthree/rgthree-comfy.git && \

    git clone https://github.com/crystian/comfyui-crystools.git


FROM python:3.10.16-slim AS models

RUN apt update && apt install -y aria2

COPY --from=registry.cn-hangzhou.aliyuncs.com/ohyee/fc-demo:fc-comfyui-sd1.5-v1 "/built-in/models/checkpoints/sd-v1-5-inpainting.ckpt" "/models/checkpoints/sd-v1-5-inpainting.ckpt"

FROM python:3.10.16-slim AS dependencies

WORKDIR /root

# 升级pip并初始化venv虚拟环境
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    python3 -m venv venv

# 安装cu128最新PyTorch及相关包
RUN --mount=type=cache,target=/root/.cache/pip \
    venv/bin/pip install --no-cache-dir torch torchvision torchaudio \
    --extra-index-url https://download.pytorch.org/whl/cu128

# issue: 历史原因，被某插件使用 @ohyee
RUN --mount=type=cache,target=/root/.cache/pip \
    venv/bin/pip install --no-cache-dir onnxruntime-gpu \
    --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

# 安装 ComfyUI源码 所使用的依赖
# 方式一: pip install动态拉取comfyui源码中的requirements.txt, 缺点：与codes层耦合，源码有新的commit会导致镜像层重新构建
ENV COMFYUI_DIR="/root/comfyui"
COPY --from=codes ${COMFYUI_DIR} ${COMFYUI_DIR}
RUN --mount=type=cache,target=/root/.cache/pip \
    find ${COMFYUI_DIR} -type f -name requirements.txt | xargs -I {} venv/bin/pip install -r {} --no-cache-dir

# 安装 ComfyUI插件 所使用的依赖; codes层变化只会导致插件依赖重新安装，不会导致torch等基础依赖重新安装
ENV COMFYUI_NODE_DIR="/root/comfyui/custom_nodes"
COPY --from=codes ${COMFYUI_NODE_DIR} ${COMFYUI_NODE_DIR}
RUN --mount=type=cache,target=/root/.cache/pip \
    find ${COMFYUI_NODE_DIR} -type f -name requirements.txt | xargs -I {} venv/bin/pip install -r {} --no-cache-dir

FROM agent AS agent

FROM python:3.10.16-slim AS base

WORKDIR /root

RUN --mount=type=cache,target=/var/cache/apt \
    apt update && \
    apt install -y \
    git curl wget jq ffmpeg gcc g++ build-essential

ENV WORK_DIR="/root"
ENV COMFYUI_DIR="${WORK_DIR}/comfyui"
ENV VENV_DIR="${WORK_DIR}/venv"
ENV AGENT_DIR="${WORK_DIR}/agent"
# MNT_DIR is initialized in s.yaml, using env var-'MODEL_ASSET_DIR'

ENV BUILT_IN_DIR="/built-in"
COPY --from=models /models ${BUILT_IN_DIR}/models
COPY --from=dependencies ${VENV_DIR} ${VENV_DIR}
COPY --from=codes ${COMFYUI_DIR} ${COMFYUI_DIR}
COPY --from=agent ${AGENT_DIR} ${AGENT_DIR}
# TODO add pip path of venv

ENV BACKEND_TYPE="comfyui"
ENTRYPOINT [ "/bin/bash", "-c", "${AGENT_DIR}/entrypoint.bash" ]
