FROM cap-demo-public-registry.cn-hangzhou.cr.aliyuncs.com/aliyunfc/funart-comfyui:v1.6.5

WORKDIR /root

ENV COMFYUI_DIR="/root/comfyui"
ENV VENV_DIR="/root/venv"

# 安装 ComfyUI-deepgpu 插件
RUN cd ${COMFYUI_DIR}/custom_nodes && \
    wget https://aiacc-inference-public-v2.oss-cn-hangzhou.aliyuncs.com/deepgpu/comfyui/nodes/20251013/ComfyUI-deepgpu.tar.gz && \
    tar -zxf ComfyUI-deepgpu.tar.gz && \
    rm -f ComfyUI-deepgpu.tar.gz

# 安装 ComfyUI-deepgpu 插件依赖
RUN --mount=type=cache,target=/root/.cache/pip \
    find ${COMFYUI_DIR}/custom_nodes/ComfyUI-deepgpu -type f -name requirements.txt | \
    xargs -I {} ${VENV_DIR}/bin/pip install -r {} --no-cache-dir

# 安装 deepgpu 专用 torch 及相关包（会覆盖基础镜像中的 torch 版本）
RUN --mount=type=cache,target=/root/.cache/pip \
    ${VENV_DIR}/bin/pip install --no-cache-dir \
    deepgpu-torch==0.1.20+torch2.9.0cu128 -f https://aiacc-inference-public-v2.oss-cn-hangzhou.aliyuncs.com/deepgpu/deepytorch/index.html \
    deepgpu-comfyui==1.5.1 -f https://aiacc-inference-public-v2.oss-cn-hangzhou.aliyuncs.com/deepgpu/comfyui/index.html
